#!/bin/tcsh
# Written by Furey.
# With additions from Tony and Alander.
# Originally written for Cleft of Dimension - Leer
# cleftofdimension.com: 9000


# Set the port number.
set port = 2528

if ( "$1" != "" ) set port="$1"

# Change to area directory.
cd ../area

# Set limits.
if ( -e shutdown.txt ) rm -f shutdown.txt

while ( 1 )
    # If you want to have logs in a different directory,
    #   change the 'set logfile' line to reflect the directory name.
    set index = 1050
#    while ( 1 )
        set logfile = ../log/doc.log
#       if ( ! -e $logfile ) break
#       @ index++
#    end

    # Run rom.
    ../src/rot $port >>&! $logfile


    # Restart, giving old connections a chance to die.
    if ( -e shutdown.txt ) then
        rm -f shutdown.txt
        exit 0
    endif
    sleep 15
end

